lug_site/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Wiki views
    url(r'^wiki/', include('lug_wiki.urls')),

    # Events views
    url(r'^events/', include('lug_events.urls')),

    # Profile and account views
    url(r'^', include('lug_people.urls')),

    # Admin interface and other internals
    url(r'^admin/', include(admin.site.urls)),

    # Template index
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
)

lug_people/models.py
import re
from django.db import models
from django.contrib.auth.models import User
from django.core import validators
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.utils.html import escape
from django.utils import timezone
import urllib

NON_USERNAME_CHARS = re.compile(r'[^\w@+.-]+')


class MemberProfile(models.Model):
    PREFERRED_NAME_CHOICES = (
        (u"nick",   u"Nickname"),
        (u"real",   u"Real Name"),
    )

    ROLE_CHOICES = (
        (u"student",    u"Student"),
        (u"alumnus",    u"Alumnus"),
        (u"faculty",    u"Faculty"),
        (u"staff",      u"Staff"),
        (u"visitor",    u"Visitor")
    )

    user            = models.OneToOneField(User, verbose_name="user")
    # Names
    nickname        = models.CharField("nickname", max_length=32,
                        help_text="IRC nickname, or other kind of online handle.")
    real_name       = models.CharField("real name", max_length=64, blank=True,
                        help_text="The name you use in person.")
    preferred_name  = models.CharField("preferred name", max_length=4,
                        choices=PREFERRED_NAME_CHOICES, default=u"nick",
                        help_text="Which name you would prefer the site to use.")
    # LUG-related organizational info
    title           = models.CharField("title", max_length=64, blank=True,
                        help_text="Official LUG title, as officer or "
                                  "committee chair.")
    ordering        = models.PositiveIntegerField("ordering", default=0,
                        help_text="Relative order on the member directory, "
                                  "for LUG officers (higher numbers appear "
                                  "first, regular members should be 0).")
    role            = models.CharField("role", max_length=8,
                        choices=ROLE_CHOICES, default=u"visitor",
                        help_text="What your relationship is to NC State. "
                                  "(If you are not affiliated with NC State "
                                  "except through the LUG, choose Visitor.)")
    # Profile miscellanea
    is_protected    = models.BooleanField("profile protected?", default=False,
                        help_text="If this is set, only LUG members can view "
                                  "your profile.")
    biography       = models.TextField("biography", blank=True,
                        help_text="Anything you would like to say about "
                                  "yourself (in WikiCreole format).")

    def __unicode__(self):
        return u"%s (%s)" % self.names if self.has_both_names else self.name

    @staticmethod
    def make_username(nickname):
        return NON_USERNAME_CHARS.sub('', nickname.lower())

    # Name-related properties
    @property
    def name(self):
        if not self.real_name or self.preferred_name == u"nick":
            return self.nickname
        else:
            return self.real_name

    @property
    def alternate_name(self):
        if not self.real_name or self.preferred_name == u"nick":
            return self.real_name
        else:
            return self.nickname

    @property
    def names(self):
        if not self.real_name or self.preferred_name == u"nick":
            return (self.nickname, self.real_name)
        else:
            return (self.real_name, self.nickname)

    @property
    def has_both_names(self):
        return bool(self.real_name)

    # Bits!
    def all_bits(self):
        return self.bit_set.all()

    def bits_as_dict(self):
        return dict((bit.slug, bit.data) for bit in self.all_bits())

    # Authentication-related properties
    @property
    def username(self):
        return self.user.username

    @property
    def email(self):
        return self.user.email


class AccountRequest(models.Model):
    STATUS_CHOICES = (
        (u"pending",    u"Pending"),
        (u"deferred",   u"Deferred"),
        (u"approved",   u"Approved")
    )

    user            = models.OneToOneField(User, verbose_name="user")
    request_date    = models.DateTimeField("request date",
                        default=timezone.now,
                        help_text="The date the user made the request.")
    status          = models.CharField("status", max_length=8,
                        choices=STATUS_CHOICES, default=u"pending",
                        help_text="The current status of the request.")
    comments        = models.TextField("comments",
                        help_text="Comments explaining who you are.")

    @property
    def names(self):
        return self.user.get_profile().names

    @property
    def username(self):
        return self.user.username

    def approve(self):
        self.user.is_active = True
        self.user.save()
        self.status = u"approved"
        self.save()

    def destroy(self):
        self.user.get_profile().delete()
        self.user.delete()
        self.delete()


class BitType(models.Model):
    BIT_FORMATS = (
        (u"freetext",   u"Free Text"),
        (u"url",        u"URL"),
        (u"username",   u"Username")
    )

    slug            = models.SlugField("slug", max_length=16,
                        help_text="An internal identifier for bits of this "
                                  "type.")
    caption         = models.CharField("caption", max_length=32,
                        help_text="Text to caption the links with on users' "
                                  "profiles.")
    ordering        = models.PositiveIntegerField("ordering", db_index=True,
                        help_text="The position of links of this type "
                                  "relative to others. Lower numbers are "
                                  "sorted first.")
    format          = models.CharField("format", max_length=8,
                        choices=BIT_FORMATS, default=u"freetext",
                        help_text="The format that this bit takes. Used "
                                  "to validate things.")
    instructions    = models.CharField("instructions", max_length=128,
                        help_text="Instructions to display for entering bits "
                                  "of this type.")
    link_template   = models.CharField("link template", max_length=240,
                        blank=True,
                        help_text="A template for turning data of this type "
                                  "into a link. Include %s where it should "
                                  "be substituted in. Obviously useless for "
                                  "URLs.")

    class Meta:
        ordering    = ('ordering', 'caption')

    def __unicode__(self):
        return self.caption


username_validator = validators.RegexValidator("^[a-zA-Z0-9_.-`]+$",
                        u"The data must be a username (if this is "
                        "your actual username, contact leafstorm so he can "
                        "fix the regex).")

url_validator = validators.URLValidator()

class Bit(models.Model):
    owner           = models.ForeignKey(MemberProfile, verbose_name="owner")
    bit_type        = models.ForeignKey(BitType, verbose_name="type")
    data            = models.CharField("data", max_length=240)

    class Meta:
        ordering    = ('bit_type__ordering', 'bit_type__caption')

    def __unicode__(self):
        return u"%s: [%s]" % (self.bit_type.caption, self.data)

    def clean(self):
        format = self.bit_type.format
        if format == u"url":
            url_validator(self.data)
        elif format == u"username":
            username_validator(self.data)

    @property
    def caption(self):
        return self.bit_type.caption

    @property
    def slug(self):
        return self.bit_type.slug

    @property
    def data_url(self):
        bt = self.bit_type
        if bt.format == u"url":
            return self.data
        elif bt.link_template:
            template = bt.link_template
            format_idx, qmark_idx = template.find("%s"), template.find("?")
            if format_idx == -1:
                return template
            elif qmark_idx != -1 and format_idx > qmark_idx:
                return template % urllib.quote_plus(self.data)
            else:
                return template % urllib.quote(self.data)
        else:
            return None

    @property
    def data_html(self):
        url = self.data_url
        if url:
            return mark_safe('<a href="%s" rel="nofollow">%s</a>' %
                             (escape(url), escape(self.data)))
        else:
            return escape(self.data)

lug_site/templates/profiles/directory.html
{% extends "layout_base.html" %}
{% load gravatar %}
{% load lug_markup %}
{% load profiles %}

{% block title %}Member Directory{% endblock title %}

{% block body %}

    <h1 class="page-header profile-header">
        Member Directory
    </h1>

    <table class="table">
        <tbody>
            {% for profile in members %}
                <tr>
                    <td style="width: 1em;">
                        <a href="{% url profile profile.username %}">
                            <img class="gravatar" alt="{{ profile.name }}'s avatar"
                                 src="{% gravatar_for_email profile.email 40 %}">
                        </a>
                    </td>
                    <td style="white-space: nowrap;">
                        <a class="username" href="{% url profile profile.username %}">
                            {{ profile.name }}
                        </a>
                        {% if profile.has_both_names %}
                            <br>
                            {{ profile.alternate_name }}
                        {% endif %}
                    </td>
                    <td style="width: 70%;">
                        {% if profile.title %}
                            <p>
                                <strong>
                                    <i class="icon-star"></i>
                                    LUG {{ profile.title }}
                                </strong>
                            </p>
                        {% endif %}
                        {{ profile.biography|wikitext|truncatewords_html:30 }}
                    </td>
                </tr>
            {% endfor %}
    </table>

    {% comment %}
    <div class="row">
        {% for profile in members %}
            <div class="span3">
                <img class="gravatar side-avatar" alt="{{ profile.name }}'s avatar"
                     src="{% gravatar_for_email profile.email 40 %}">
                <p>
                    <a href="{% url profile profile.username %}">
                        <strong>{{ profile.name }}</strong>
                    </a><br>
                    {% if profile.has_both_names %}
                        {{ profile.alternate_name }}<br>
                    {% endif %}
                    {% if profile.title %}
                        <i class="icon-star"></i>
                        LUG {{ profile.title }}
                    {% endif %}
                </p>
            </div>
        {% endfor %}
    </div>
    {% endcomment %}

{% endblock body %}

lug_site/templates/profiles/edit.html
{% extends "layout_base.html" %}
{% load bootstrap_toolkit %}
{% load gravatar %}

{% block title %}Edit Profile{% endblock title %}

{% block body %}

   <h1 class="page-header profile-header">
        <img class="gravatar" alt="{{ profile.name }}'s avatar" src="{% gravatar_for_email profile.email 40 %}">
        <strong>{{ profile.name }}</strong>
        {% if profile.has_both_names %}
        ({{ profile.alternate_name }})
        {% endif %}
        <a href="{% url profile profile.username %}" class="btn btn-primary" style="float: right;">
            <i class="icon-arrow-left icon-white"></i> Back to Profile
        </a>
    </h1>

    <form action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="span5 profile-bio">
                <h2>Basic Information</h2>

                {{ form|as_bootstrap }}
            </div>

            <div class="span7 profile-bits">
                <h2>Bits</h2>

                {{ bit_forms.management_form|as_bootstrap }}
                {% if bit_forms.non_field_errors %}
                    {% include "bootstrap_toolkit/non_field_errors.html" with form=bit_forms %}
                {% endif %}

                <table class="table form-grid">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th colspan="2">Data</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for bit_form in bit_forms.forms %}
                        <tr>
                            <td class="control-group{% if bit_form.bit_type.errors %} error{% endif %}">
                                {{ bit_form.bit_type }}
                                {% include "bootstrap_toolkit/field_errors.html" with field=bit_form.bit_type inline=False %}
                            </td>
                            <td class="control-group{% if bit_form.data.errors %} error{% endif %}">
                                {{ bit_form.data }}
                                {% include "bootstrap_toolkit/field_errors.html" with field=bit_form.data inline=False %}
                            </td>
                            <td class="symbolic-checkbox">
                                {{ bit_form.id }}
                                {{ bit_form.owner }}
                                <label for="{{ bit_form.DELETE.auto_id }}">
                                    {{ bit_form.DELETE }}
                                    <i class="icon-trash"></i>
                                </label>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="row">
            <div class="span12">
                <div class="form-actions">
                    <button class="btn btn-success" type="submit">
                        <i class="icon-ok icon-white"></i>
                        Save Profile
                    </button>
                </div>
            </div>
        </div>
    </form>

{% endblock body %}

lug_site/templates/profiles/link.html
{% load gravatar %}
{% if link %}<a href="{% url profile profile.username %}">{% endif %}
    <img class="gravatar" alt="{{ profile.name }}'s avatar" src="{% gravatar_for_email profile.email 24 %}">
    {{ profile.name }}
{% if link %}</a>{% endif %}

lug_site/templates/profiles/show.html
{% extends "layout_base.html" %}
{% load gravatar %}
{% load lug_markup %}

{% block title %}{{ profile }}{% endblock title %}

{% block body %}

   <h1 class="page-header profile-header">
        <img class="gravatar" alt="{{ profile.name }}'s avatar" src="{% gravatar_for_email profile.email 40 %}">
        <strong>{{ profile.name }}</strong>
        {% if profile.has_both_names %}
            ({{ profile.alternate_name }})
        {% endif %}
        {% if profile.user == user %}
            <div class="btn-group pull-right">
                <a href="{% url profile_edit %}" class="btn btn-primary">
                    <i class="icon-pencil icon-white"></i> Edit Profile
                </a>
            </div>
        {% endif %}
    </h1>

    <div class="row">
        <div class="span6 profile-bio">
            {% if profile.title %}
            <p style="font-weight: bold;">
                <i class="icon-star"></i>
                LUG {{ profile.title }}
            </p>
            {% endif %}

            <h2>Biography</h2>

            {% if profile.biography %}
            {{ profile.biography|wikitext }}
            {% else %}
            <p>
                ({{ profile.name }} hasn't written a biography yet.)
            </p>
            {% endif %}
        </div>

        <div class="span6 profile-bits">
            <h2>More Information</h2>

            <table class="bits table table-condensed">
                <tbody>
                    <tr>
                        <th>Role:</th>
                        <td>{{ profile.get_role_display }}</td>
                    </tr>
                    {% for bit in profile.all_bits %}
                    <tr>
                        <th>{{ bit.bit_type.caption }}:</th>
                        <td>{{ bit.data_html }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock body %}